#!/usr/bin/env ruby
require 'bundler'
Bundler.require

require_relative '../providers/client'
require_relative '../providers/invoice'

host = ENV["RABBIT_HOST"] || 'localhost'
port = ENV["RABBIT_PORT"] || 5672
user = ENV["RABBIT_USER"] || 'guest'
password = ENV["RABBIT_PASSWORD"] || 'guest'

puts "Starting up service..."
sleep 10 # give rabbitmq time to get up

connection = Bunny.new("amqp://#{user}:#{password}@#{host}:#{port}")
connection.start

Thread.new{ Invoice.new(connection.create_channel).start }
Thread.new{ Client.new(connection.create_channel).start }

sleep
